#!/usr/bin/env python3
"""
QA Automation Script for @Mention Component

This script demonstrates Claude Computer Use for automated QA testing,
as shown in the lesson. It tests the @mention component and generates a report.
"""

import os
import sys
from computer_use_client import ComputerUseClient


# The QA test prompt from the lesson
QA_TEST_PROMPT = """
You are performing QA testing on a React component that implements @mention functionality.

**Component URL:** http://localhost:8000

**Testing Process:**
1. Navigate to the component URL in a browser
2. Observe the component's behavior
3. Execute each test case systematically
4. Document the results
5. Take screenshots of any failures

**Test Cases:**

**Test 1: Verify Autocomplete Appears**
- Type "@" in the text area
- Expected: Autocomplete dropdown appears with suggestions
- Result: PASS/FAIL

**Test 2: Verify Enter Key Inserts Mention**
- Type "@" to show autocomplete
- Press Enter to select the first option
- Expected: The mention is inserted into the text (e.g., "@john ")
- Result: PASS/FAIL

**Test 3: Verify Backspace with Multiple Mentions**
- Insert two mentions (type "@", select one, type "@" again, select another)
- Press Backspace after the second mention
- Expected: Autocomplete should appear directly below/near the cursor
- Actual Bug: Autocomplete appears in the top-left corner of the screen
- Result: PASS/FAIL

**Test 4: Verify Escape Key Closes Autocomplete**
- Type "@" to show autocomplete
- Press Escape
- Expected: Autocomplete should close
- Result: PASS/FAIL

**Test 5: Verify Arrow Keys Navigate Autocomplete**
- Type "@" to show autocomplete
- Press Arrow Down key
- Expected: Selection moves to next item
- Result: PASS/FAIL

---

**Output Format:**
After completing all tests, provide a concise report in this format:

## QA Test Report: @Mention Component

### Summary
- Total Tests: X
- Passed: X
- Failed: X

### Test Results

**Test 1: Autocomplete Appears** - PASS/FAIL
- Details: ...

**Test 2: Enter Inserts Mention** - PASS/FAIL
- Details: ...

**Test 3: Backspace with Multiple Mentions** - PASS/FAIL
- Details: ...
- Bug Found: [description if failed]

**Test 4: Escape Closes Autocomplete** - PASS/FAIL
- Details: ...

**Test 5: Arrow Keys Navigate** - PASS/FAIL
- Details: ...

### Recommendations
- [List any bugs that need fixing]
- [Suggest improvements]

---

**Important:**
- Be thorough but efficient
- Document exact steps taken
- Note any unexpected behavior
- Take your time to observe results

Begin testing now.
"""


def run_qa_tests():
    """Run automated QA tests using Claude Computer Use."""

    print("="*70)
    print("🤖 Claude Computer Use - Automated QA Testing")
    print("="*70)
    print("\nTest Target: @Mention Component")
    print("URL: http://localhost:8000")
    print("\nThis will use Claude to automatically:")
    print("  1. Open the component in a browser")
    print("  2. Execute all test cases")
    print("  3. Document results")
    print("  4. Generate QA report")
    print("\n" + "="*70 + "\n")

    # Check for API key
    api_key = os.environ.get('ANTHROPIC_API_KEY')
    if not api_key:
        print("❌ Error: ANTHROPIC_API_KEY environment variable not set")
        print("\nTo run this test:")
        print("  export ANTHROPIC_API_KEY='your-api-key-here'")
        print("  python qa_test_mention_component.py")
        sys.exit(1)

    # Check if test server is running
    print("⚠️  Make sure the test server is running:")
    print("   python test-app/server.py")
    print("\nPress Enter when ready to start testing...")
    input()

    # Initialize Computer Use client
    print("\n🚀 Initializing Claude Computer Use client...\n")
    client = ComputerUseClient(api_key=api_key)

    # Run QA tests
    print("📋 Starting automated QA tests...\n")
    print("-" * 70)

    try:
        responses = client.run_task(QA_TEST_PROMPT, max_iterations=30)

        # Print final report
        print("\n" + "="*70)
        print("📊 QA TEST COMPLETE")
        print("="*70)

        if responses:
            final_report = responses[-1]
            print("\n" + final_report)

        # Save report to file
        report_file = "results/qa_report_mention_component.txt"
        os.makedirs("results", exist_ok=True)

        with open(report_file, 'w') as f:
            f.write("="*70 + "\n")
            f.write("QA Test Report: @Mention Component\n")
            f.write("Generated by Claude Computer Use\n")
            f.write("="*70 + "\n\n")

            for i, response in enumerate(responses, 1):
                f.write(f"\n--- Response {i} ---\n")
                f.write(response)
                f.write("\n")

        print(f"\n✅ Report saved to: {report_file}")

    except KeyboardInterrupt:
        print("\n\n⚠️  Testing interrupted by user")
    except Exception as e:
        print(f"\n❌ Error during testing: {e}")
        import traceback
        traceback.print_exc()

    print("\n" + "="*70)
    print("Testing complete!")
    print("="*70 + "\n")


if __name__ == "__main__":
    run_qa_tests()
